Cache node installation package

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 
 set -e            # fail fast
-set -o pipefail   # don't ignore exit codes when piping output
+set -o pipefail   # dont ignore exit codes when piping output
 # set -x          # enable debugging
 
 # Configure directories
@@ -42,9 +42,15 @@ else
 fi
 
 # Download node from Heroku's S3 mirror of nodejs.org/dist
-status "Downloading and installing node"
-node_url="http://s3pository.heroku.com/node/v$node_version/node-v$node_version-linux-x64.tar.gz"
-curl $node_url -s -o - | tar xzf - -C $build_dir
+if [ ! -f "$cache_dir/node-v$node_version-linux-x64.tar.gz" ]; then
+  status "Downloading and installing node (first run)"
+  node_url="http://s3pository.heroku.com/node/v$node_version/node-v$node_version-linux-x64.tar.gz"
+  curl $node_url -s -o - | tee $cache_dir/node-v$node_version-linux-x64.tar.gz | tar xzf - -C $build_dir
+else
+  status "Installing node"
+  node_url="http://s3pository.heroku.com/node/v$node_version/node-v$node_version-linux-x64.tar.gz"
+  tar xzf $cache_dir/node-v$node_version-linux-x64.tar.gz -C $build_dir
+fi
 
 # Move node (and npm) into ./vendor and make them executable
 mkdir -p $build_dir/vendor
